### ISSUE TITLE
[Bug] Last command not found not persited

### ISSUE THREAD

**Issue by easycom-xmedias** [synolia/SyliusSchedulerCommandPlugin#30]
**Describe the bug**
If shceduled command not fount and run at last, error code is not saved on database.

**To Reproduce**
1. Register new sheduled command 
2. Force to have non existant command (e.g: asset:installs)
3. Run ` bin/console synolia:scheduler-run`
4. Check last return code

**Expected behavior**
The sheduled command should have `-1` as last return code

**Additional context**
In the case on last command, there is no `flush()` instruction.

**Comment by oallain** [comment]
Resolved by #31
