### ISSUE TITLE
[Feature] Allow process timeout override per command

### ISSUE THREAD

**Issue by markbeazley** [synolia/SyliusSchedulerCommandPlugin#38]
I have a long running command scheduled, which it itself runs a set of other console commands (runs a command for each channel and locale combination) and it regularly hits the 60 second time out and doesn't finish running.

I'm thinking it should be possible to pass a time out in seconds from the admin through to `setTimeout()` on the process, which can also take null to disable, however the [Symfony docs](https://symfony.com/doc/current/components/process.html#process-timeout) say that for longer tasks you have to also check the timeout manually so not sure how practical that is. I also realise there might be issues if the timeout is longer than the interval between two runs of the command.

**Comment by TheGrimmChester** [comment]
Timeout has been disabled on the master branch (be carefull if you use it, lots of breaking changes) and doctrine timeout between two commands is currently resolved inside #47. It is not currently planned to configure per command timeout but we will look into it if it is important.
