### ISSUE TITLE
purge-history Command

### ISSUE THREAD

**Issue by Audax23** [synolia/SyliusSchedulerCommandPlugin#81]
Hi,

I would like to purge the history however when I try to run the symfony command I get this message as a response.

php bin/console synolia:scheduler:purge-history --all

**There are no commands defined in the "synolia:scheduler" namespace.

Did you mean this?
synolia**

Do I have to activate something in the configuration?
I'm on Sylius 1.10.7
Thanks

**Comment by oallain** [comment]
Hello @Audax23 ,

Purge command was introduced in [v3.1.0](https://github.com/synolia/SyliusSchedulerCommandPlugin/releases/tag/v3.1.0) and this version [support Sylius 1.10](https://github.com/synolia/SyliusSchedulerCommandPlugin/blob/v3.1.0/composer.json#L11).

I have made a test:
```
$ composer show sylius/sylius | grep versions
versions : * v1.10.7
$ php bin/console synolia:scheduler:purge-history

 ! [NOTE] Schedules with states ["finished"] lesser than 3 days(s) (2023-04-26) will be purged.                         

```

What is your version of this plugin ?
Command `composer show synolia/sylius-scheduler-command-plugin | grep versions`

Regards,

**Comment by Audax23** [comment]
Hello @oallain,

Thanks for your response and help,
the plugin is in version 3.0.1, which explains the non-existence of the command, I will update it.
Sorry, I didn't think to check when this Symfony command was introduced.
Thanks again,
Have a good day
